spring:
  application:
    name: 2024-spring-security-session-ex

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:core
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379
  session:
    timeout: 30m
    redis:
      namespace: spring:session

#  session:
#    timeout: 86400

#server:
#  servlet:
#    session:
#      cookie:
#        max-age: 172800
